import {
  AGENT_SESSION_ACCEPTED_SEND_RUNTIME_CAPABILITY,
  AGENT_SESSION_BACKGROUND_TASK_ROW_STOP_CAPABILITY,
  AGENT_SESSION_BACKGROUND_TASK_STOP_CAPABILITY,
  AGENT_SESSION_CONVERSATION_OUTLINE_RUNTIME_CAPABILITY,
  AGENT_SESSION_CREATE_TAB_ID_RUNTIME_CAPABILITY,
  AGENT_SESSION_PENDING_SEND_RESULT_RUNTIME_CAPABILITY,
  AGENT_SESSION_QUESTION_ANSWERS_RUNTIME_CAPABILITY,
  AGENT_SESSION_QUEUED_MESSAGES_RUNTIME_CAPABILITY,
  AGENT_SESSION_REWIND_RUNTIME_CAPABILITY,
  AGENT_SESSION_SEND_ANSWERS_PROOF_RUNTIME_CAPABILITY,
  AGENT_SESSION_TURN_ITEM_CAPABILITY,
  STRUCTURED_AGENT_SESSION_REGISTERED_AGENTS_RUNTIME_CAPABILITY,
  STRUCTURED_AGENT_SESSION_RUNTIME_CAPABILITY,
  type RuntimeCapability
} from '../shared/protocol-version'

export function agentSessionCliCapabilities(method: string): readonly RuntimeCapability[] {
  return method.startsWith('agentSession.') ||
    method.startsWith('session.tabs.') ||
    method === 'aiVault.listSessions'
    ? [
        STRUCTURED_AGENT_SESSION_RUNTIME_CAPABILITY,
        STRUCTURED_AGENT_SESSION_REGISTERED_AGENTS_RUNTIME_CAPABILITY,
        AGENT_SESSION_PENDING_SEND_RESULT_RUNTIME_CAPABILITY,
        AGENT_SESSION_ACCEPTED_SEND_RUNTIME_CAPABILITY,
        AGENT_SESSION_SEND_ANSWERS_PROOF_RUNTIME_CAPABILITY,
        AGENT_SESSION_QUEUED_MESSAGES_RUNTIME_CAPABILITY,
        AGENT_SESSION_CONVERSATION_OUTLINE_RUNTIME_CAPABILITY,
        AGENT_SESSION_REWIND_RUNTIME_CAPABILITY,
        AGENT_SESSION_TURN_ITEM_CAPABILITY,
        AGENT_SESSION_BACKGROUND_TASK_STOP_CAPABILITY,
        AGENT_SESSION_QUESTION_ANSWERS_RUNTIME_CAPABILITY,
        AGENT_SESSION_BACKGROUND_TASK_ROW_STOP_CAPABILITY,
        AGENT_SESSION_CREATE_TAB_ID_RUNTIME_CAPABILITY
      ]
    : []
}
