import type { HandlerGroup } from './handler-group-manifest'

export const AGENT_SESSION_HANDLER_GROUPS: readonly HandlerGroup[] = [
  {
    name: 'agent-sessions',
    keys: [
      'agent hooks workspace-check',
      'agent hooks setup-imports',
      'agent hooks issue-read',
      'agent hooks issue-write',
      'terminal daemon list',
      'terminal daemon stop',
      'terminal daemon stop-many',
      'agent terminal create',
      'agent terminal ensure',
      'agent session close',
      'agent session reveal',
      'terminal side-effects',
      'terminal workspace-hosts',
      'terminal fit-overrides',
      'terminal drivers',
      'agent awake status',
      'agent status list',
      'agent status dismiss',
      'agent status migration',
      'agent history delete',
      'agent history subagents',
      'terminal clear',
      'terminal reset-input',
      'terminal inspect-process',
      'terminal identity',
      'terminal agent-status',
      'terminal restore-fit',
      'terminal display-mode',
      'terminal set-display-mode',
      'terminal tabs',
      'terminal move-tab',
      'terminal set-tab',
      'terminal set-layout',
      'agent history list',
      'agent history titles',
      'agent history resume-plan',
      'agent history read',
      'agent session agents',
      'agent session create-support',
      'agent session history',
      'agent session options',
      'agent session commands',
      'agent session outline',
      'agent session handoff-status',
      'agent session model-catalog',
      'agent session create',
      'agent session send',
      'agent session cancel',
      'agent session respond-approval',
      'agent session respond-question',
      'agent session set-option',
      'agent session conversation-command',
      'agent session rewind',
      'agent session thread-goal',
      'agent session queued-send',
      'agent session queued-delete',
      'agent session queued-resume',
      'agent session restart-list',
      'agent session restart-dismiss',
      'agent session restart-continue'
    ],
    load: async () => (await import('./handlers/agent-sessions.js')).AGENT_SESSION_HANDLERS
  }
]
