import type { HandlerGroup } from './handler-group-manifest'

export const APP_LIFECYCLE_HANDLER_GROUPS: readonly HandlerGroup[] = [
  {
    name: 'app-lifecycle',
    keys: [
      'app cli install',
      'app cli remove',
      'app cli status',
      'app diagnostics collect',
      'app diagnostics delete',
      'app diagnostics discard',
      'app diagnostics preview',
      'app diagnostics status',
      'app diagnostics upload',
      'app dock-badge',
      'app feature-assets',
      'app feedback submit',
      'app keyboard-layout',
      'app keyboard-source',
      'app markdown-directory',
      'app native-menu',
      'app onboarding get',
      'app onboarding update',
      'app pet import',
      'app pet preferences',
      'app pet read',
      'app pet remove',
      'app pet set',
      'app platform',
      'app quit',
      'app relaunch',
      'app reload',
      'app repo-color',
      'app restart',
      'app shell exists',
      'app shell open-path',
      'app shell open-url',
      'app shell select',
      'app shells',
      'app star-prompt',
      'app stats',
      'app status',
      'app telemetry acknowledge',
      'app telemetry set',
      'app telemetry status',
      'app telemetry track',
      'app update builds',
      'app update check',
      'app update dismiss-available',
      'app update dismiss-nudge',
      'app update download',
      'app update install',
      'app update instructions',
      'app update show-package',
      'app update status',
      'app update version',
      'app vault clear-index',
      'app vault first-prompt',
      'app vault status',
      'app view control',
      'app wsl-distros'
    ],
    load: async () => (await import('./handlers/app-lifecycle.js')).APP_LIFECYCLE_HANDLERS
  }
]
