import { TERMINAL_PRIVATE_SPAWN_COMMAND_SPECS } from './terminal-private-spawn'
import { TERMINAL_LISTENER_COUNT_COMMAND_SPECS } from './terminal-listener-count'
import { TERMINAL_HOST_VIEWPORT_COMMAND_SPECS } from './terminal-host-viewport'
import { TERMINAL_PREVIEW_DATA_WATCH_COMMAND_SPECS } from './terminal-preview-data-watch'
import { TERMINAL_HOST_RESIZE_COMMAND_SPECS } from './terminal-host-resize'
import { TERMINAL_RENDERER_REPLAY_WATCH_COMMAND_SPECS } from './terminal-renderer-replay-watch'
import { TERMINAL_RENDERER_DATA_WATCH_COMMAND_SPECS } from './terminal-renderer-data-watch'
import { RENDERER_DELIVERY_RESYNC_WATCH_COMMAND_SPECS } from './renderer-delivery-resync-watch'
import { TERMINAL_CONTROL_WATCH_COMMAND_SPECS } from './terminal-control-watch'
import { TERMINAL_RENDER_EVIDENCE_COMMAND_SPECS } from './terminal-render-evidence'
import { DAEMON_FOLDER_ACCESS_COMMAND_SPECS } from './daemon-folder-access'
import { TERMINAL_SPAWN_WATCH_COMMAND_SPECS } from './terminal-spawn-watch'
import { TERMINAL_EXIT_WATCH_COMMAND_SPECS } from './terminal-exit-watch'
import { DAEMON_RESTART_COMMAND_SPECS } from './daemon-restart'
import { TERMINAL_EFFECTS_WATCH_COMMAND_SPECS } from './terminal-effects-watch'
import { AGENT_WORKER_RECOVERY_WATCH_COMMAND_SPECS } from './agent-worker-recovery-watch'
import { AGENT_MIGRATION_WATCH_COMMAND_SPECS } from './agent-migration-watch'
import { AGENT_STATUS_WATCH_COMMAND_SPECS } from './agent-status-watch'
import { STRUCTURED_HELD_WATCH_COMMAND_SPECS } from './structured-held-watch'
import { REMOTE_WORKSPACE_WATCH_COMMAND_SPECS } from './remote-workspace-watch'
import { AGENT_AWAKE_WATCH_COMMAND_SPECS } from './agent-awake-watch'
import { TERMINAL_PRESENTATION_WATCH_COMMAND_SPECS } from './terminal-presentation-watch'
import { TERMINAL_PRESENTATION_WAIT_COMMAND_SPECS } from './terminal-presentation-wait'
import { TERMINAL_PTY_INPUT_COMMAND_SPECS } from './terminal-pty-input'
import { REMOTE_WORKSPACE_PUBLISH_COMMAND_SPECS } from './remote-workspace-publish'
import { AI_VAULT_LIST_CANCEL_COMMAND_SPECS } from './ai-vault-list-cancel'
import { TERMINAL_PREVIEW_INPUT_COMMAND_SPECS } from './terminal-preview-input'
import { TERMINAL_PTY_STOP_COMMAND_SPECS } from './terminal-pty-stop'
import { WORKSPACE_SESSION_WRITE_COMMAND_SPECS } from './workspace-session-write'
import { AGENT_PANE_AUTHORITY_COMMAND_SPECS } from './agent-pane-authority'
import { NATIVE_CHAT_WATCH_COMMAND_SPECS } from './native-chat-watch'

export const AGENT_SESSION_RUNTIME_COMMAND_SPECS = [
  ...TERMINAL_PRIVATE_SPAWN_COMMAND_SPECS,
  ...TERMINAL_LISTENER_COUNT_COMMAND_SPECS,
  ...AGENT_WORKER_RECOVERY_WATCH_COMMAND_SPECS,
  ...TERMINAL_EFFECTS_WATCH_COMMAND_SPECS,
  ...TERMINAL_EXIT_WATCH_COMMAND_SPECS,
  ...TERMINAL_SPAWN_WATCH_COMMAND_SPECS,
  ...DAEMON_RESTART_COMMAND_SPECS,
  ...DAEMON_FOLDER_ACCESS_COMMAND_SPECS,
  ...TERMINAL_RENDER_EVIDENCE_COMMAND_SPECS,
  ...RENDERER_DELIVERY_RESYNC_WATCH_COMMAND_SPECS,
  ...TERMINAL_RENDERER_DATA_WATCH_COMMAND_SPECS,
  ...TERMINAL_RENDERER_REPLAY_WATCH_COMMAND_SPECS,
  ...TERMINAL_HOST_RESIZE_COMMAND_SPECS,
  ...TERMINAL_PREVIEW_DATA_WATCH_COMMAND_SPECS,
  ...TERMINAL_HOST_VIEWPORT_COMMAND_SPECS,
  ...TERMINAL_CONTROL_WATCH_COMMAND_SPECS,
  ...AGENT_MIGRATION_WATCH_COMMAND_SPECS,
  ...AGENT_STATUS_WATCH_COMMAND_SPECS,
  ...STRUCTURED_HELD_WATCH_COMMAND_SPECS,
  ...REMOTE_WORKSPACE_WATCH_COMMAND_SPECS,
  ...AGENT_AWAKE_WATCH_COMMAND_SPECS,
  ...TERMINAL_PRESENTATION_WATCH_COMMAND_SPECS,
  ...TERMINAL_PRESENTATION_WAIT_COMMAND_SPECS,
  ...TERMINAL_PTY_INPUT_COMMAND_SPECS,
  ...REMOTE_WORKSPACE_PUBLISH_COMMAND_SPECS,
  ...AI_VAULT_LIST_CANCEL_COMMAND_SPECS,
  ...TERMINAL_PREVIEW_INPUT_COMMAND_SPECS,
  ...TERMINAL_PTY_STOP_COMMAND_SPECS,
  ...WORKSPACE_SESSION_WRITE_COMMAND_SPECS,
  ...AGENT_PANE_AUTHORITY_COMMAND_SPECS,
  ...NATIVE_CHAT_WATCH_COMMAND_SPECS
]
