import { WORKSPACE_CRASH_REPORT_COMMAND_SPECS } from './workspace-crash-reports'
import { WORKSPACE_GIT_STARTUP_COMMAND_SPECS } from './workspace-git-startup'
import { WORKSPACE_CLEANUP_DISMISSAL_COMMAND_SPECS } from './workspace-cleanup-dismissals'
import { WORKSPACE_LINEAR_ISSUE_COMMAND_SPECS } from './workspace-linear-issues'
import { WORKSPACE_CACHED_SCAN_COMMAND_SPECS } from './workspace-cached-scans'
import { WORKSPACE_GITHUB_ACCOUNT_COMMAND_SPECS } from './workspace-github-account'
import { WORKSPACE_GITLAB_INSPECTION_COMMAND_SPECS } from './workspace-gitlab-inspection'
import { WORKSPACE_KEYBINDING_FILE_COMMAND_SPECS } from './workspace-keybinding-file'
import { WORKSPACE_GIT_IGNORE_COMMAND_SPECS } from './workspace-git-ignore'
import { WORKSPACE_GIT_GENERATION_COMMAND_SPECS } from './workspace-git-generation'
import type { CommandSpec } from '../args'
import { WORKSPACE_HOSTED_REVIEW_COMMAND_SPECS } from './workspace-hosted-review'
import { WORKSPACE_BITBUCKET_COMMAND_SPECS } from './workspace-bitbucket'
import { WORKSPACE_CATALOG_COMMAND_SPECS } from './workspace-catalog'
import { WORKSPACE_FILE_COMMAND_SPECS } from './workspace-file'
import { WORKSPACE_GIT_READ_COMMAND_SPECS } from './workspace-git-read'
import { WORKSPACE_GIT_WRITE_COMMAND_SPECS } from './workspace-git-write'
import { WORKSPACE_FOLDER_COMMAND_SPECS } from './workspace-folder'
import { WORKSPACE_PROJECT_GROUP_COMMAND_SPECS } from './workspace-project-group'
import { WORKSPACE_REPO_DATA_COMMAND_SPECS } from './workspace-repo-data'
import { WORKSPACE_PROJECT_DATA_COMMAND_SPECS } from './workspace-project-data'
import { WORKSPACE_PORTS_COMMAND_SPECS } from './workspace-ports'
import { WORKSPACE_GITHUB_ISSUE_COMMAND_SPECS } from './workspace-github-issue'
import { WORKSPACE_GITHUB_REVIEW_COMMAND_SPECS } from './workspace-github-review'
import { WORKSPACE_GITHUB_REVIEW_READ_COMMAND_SPECS } from './workspace-github-review-read'
import { WORKSPACE_GITHUB_WORK_ITEMS_COMMAND_SPECS_1 } from './workspace-github-work-items-1'
import { WORKSPACE_GITHUB_WORK_ITEMS_COMMAND_SPECS_2 } from './workspace-github-work-items-2'
import { WORKSPACE_GITHUB_PROJECT_COMMAND_SPECS_1 } from './workspace-github-project-1'
import { WORKSPACE_GITHUB_PROJECT_COMMAND_SPECS_2 } from './workspace-github-project-2'
import { WORKSPACE_GITLAB_COMMAND_SPECS_1 } from './workspace-gitlab-1'
import { WORKSPACE_GITLAB_COMMAND_SPECS_2 } from './workspace-gitlab-2'
import { WORKSPACE_GITLAB_COMMAND_SPECS_3 } from './workspace-gitlab-3'
import { WORKSPACE_JIRA_COMMAND_SPECS_1 } from './workspace-jira-1'
import { WORKSPACE_JIRA_COMMAND_SPECS_2 } from './workspace-jira-2'
import { WORKSPACE_LINEAR_DATA_COMMAND_SPECS } from './workspace-linear-data'
import { WORKSPACE_INTEGRATION_COMMAND_SPECS } from './workspace-integrations'

export const WORKSPACE_DATA_COMMAND_SPECS: CommandSpec[] = [
  ...WORKSPACE_CRASH_REPORT_COMMAND_SPECS,
  ...WORKSPACE_GIT_STARTUP_COMMAND_SPECS,
  ...WORKSPACE_LINEAR_ISSUE_COMMAND_SPECS,
  ...WORKSPACE_CACHED_SCAN_COMMAND_SPECS,
  ...WORKSPACE_CLEANUP_DISMISSAL_COMMAND_SPECS,
  ...WORKSPACE_GITHUB_ACCOUNT_COMMAND_SPECS,
  ...WORKSPACE_GITLAB_INSPECTION_COMMAND_SPECS,
  ...WORKSPACE_KEYBINDING_FILE_COMMAND_SPECS,
  ...WORKSPACE_GIT_IGNORE_COMMAND_SPECS,
  ...WORKSPACE_GIT_GENERATION_COMMAND_SPECS,
  ...WORKSPACE_HOSTED_REVIEW_COMMAND_SPECS,
  ...WORKSPACE_BITBUCKET_COMMAND_SPECS,
  ...WORKSPACE_CATALOG_COMMAND_SPECS,
  ...WORKSPACE_FILE_COMMAND_SPECS,
  ...WORKSPACE_GIT_READ_COMMAND_SPECS,
  ...WORKSPACE_GIT_WRITE_COMMAND_SPECS,
  ...WORKSPACE_FOLDER_COMMAND_SPECS,
  ...WORKSPACE_PROJECT_GROUP_COMMAND_SPECS,
  ...WORKSPACE_REPO_DATA_COMMAND_SPECS,
  ...WORKSPACE_PROJECT_DATA_COMMAND_SPECS,
  ...WORKSPACE_PORTS_COMMAND_SPECS,
  ...WORKSPACE_GITHUB_ISSUE_COMMAND_SPECS,
  ...WORKSPACE_GITHUB_REVIEW_COMMAND_SPECS,
  ...WORKSPACE_GITHUB_REVIEW_READ_COMMAND_SPECS,
  ...WORKSPACE_GITHUB_WORK_ITEMS_COMMAND_SPECS_1,
  ...WORKSPACE_GITHUB_WORK_ITEMS_COMMAND_SPECS_2,
  ...WORKSPACE_GITHUB_PROJECT_COMMAND_SPECS_1,
  ...WORKSPACE_GITHUB_PROJECT_COMMAND_SPECS_2,
  ...WORKSPACE_GITLAB_COMMAND_SPECS_1,
  ...WORKSPACE_GITLAB_COMMAND_SPECS_2,
  ...WORKSPACE_GITLAB_COMMAND_SPECS_3,
  ...WORKSPACE_JIRA_COMMAND_SPECS_1,
  ...WORKSPACE_JIRA_COMMAND_SPECS_2,
  ...WORKSPACE_LINEAR_DATA_COMMAND_SPECS,
  ...WORKSPACE_INTEGRATION_COMMAND_SPECS
]
