import { WORKSPACE_GIT_STATUS_COMMAND_SPECS } from './workspace-git-status'
import { WORKSPACE_LOG_TAIL_COMMAND_SPECS } from './workspace-log-tail'
import { WORKSPACE_NOTEBOOK_KERNEL_COMMAND_SPECS } from './workspace-notebook-kernel'
import { WORKSPACE_LOCAL_CLONE_COMMAND_SPECS } from './workspace-local-clone'
import { WORKSPACE_REMOTE_CLONE_COMMAND_SPECS } from './workspace-remote-clone'
import { WORKSPACE_FILE_SEARCH_COMMAND_SPECS } from './workspace-file-search'
import { WORKSPACE_NESTED_SCAN_COMMAND_SPECS } from './workspace-nested-scan'
import { WORKSPACE_FILE_LIST_COMMAND_SPECS } from './workspace-file-list'
import { WORKSPACE_DESKTOP_ADOPT_COMMAND_SPECS } from './workspace-desktop-adopt'
import { WORKSPACE_DESKTOP_REMOVE_COMMAND_SPECS } from './workspace-desktop-remove'
import { WORKSPACE_DESKTOP_CREATE_COMMAND_SPECS } from './workspace-desktop-create'
import { WORKSPACE_LINEAGE_COMMAND_SPECS } from './workspace-lineage'
import { WORKSPACE_SPACE_SCAN_COMMAND_SPECS } from './workspace-space-scan'
import { WORKSPACE_LOCALHOST_LABEL_COMMAND_SPECS } from './workspace-localhost-label'
import { WORKSPACE_GITHUB_REFRESH_COMMAND_SPECS } from './workspace-github-refresh'
import { WORKSPACE_REPO_CREATE_REMOTE_COMMAND_SPECS } from './workspace-repo-create-remote'
import { WORKSPACE_REPO_ADD_COMMAND_SPECS } from './workspace-repo-add'
import { WORKSPACE_REPO_FOLDER_PICKER_COMMAND_SPECS } from './workspace-repo-folder-picker'
import { WORKSPACE_WORKTREE_FORGET_COMMAND_SPECS } from './workspace-worktree-forget'
import { WORKSPACE_CLEANUP_SCAN_COMMAND_SPECS } from './workspace-cleanup-scan'
import { WORKSPACE_REPO_ICON_PICKER_COMMAND_SPECS } from './workspace-repo-icon-picker'
import { WORKSPACE_DIAGNOSTIC_PREVIEW_COMMAND_SPECS } from './workspace-diagnostic-preview'
import { WORKSPACE_NOTEBOOK_ENVIRONMENT_COMMAND_SPECS } from './workspace-notebook-environments'
import { WORKSPACE_SHELL_ACTION_COMMAND_SPECS } from './workspace-shell-actions'
import { WORKSPACE_IMPORT_PREVIEW_COMMAND_SPECS } from './workspace-import-previews'
import { WORKSPACE_REPO_UPDATE_COMMAND_SPECS } from './workspace-repo-update'
import { WORKSPACE_REPO_USERNAME_COMMAND_SPECS } from './workspace-repo-username'
import { WORKSPACE_DESKTOP_META_COMMAND_SPECS } from './workspace-desktop-meta'
import { WORKSPACE_VISIBLE_WORKTREE_COMMAND_SPECS } from './workspace-visible-worktrees'
import { WORKSPACE_HOST_PATH_COMMAND_SPECS } from './workspace-host-path'
import { WORKSPACE_CRASH_REPORT_COMMAND_SPECS } from './workspace-crash-reports'
import { WORKSPACE_GIT_STARTUP_COMMAND_SPECS } from './workspace-git-startup'
import { WORKSPACE_CLEANUP_DISMISSAL_COMMAND_SPECS } from './workspace-cleanup-dismissals'
import { WORKSPACE_LINEAR_ISSUE_COMMAND_SPECS } from './workspace-linear-issues'
import { WORKSPACE_CACHED_SCAN_COMMAND_SPECS } from './workspace-cached-scans'
import { WORKSPACE_GITHUB_ACCOUNT_COMMAND_SPECS } from './workspace-github-account'
import { WORKSPACE_GITLAB_INSPECTION_COMMAND_SPECS } from './workspace-gitlab-inspection'
import { WORKSPACE_KEYBINDING_FILE_COMMAND_SPECS } from './workspace-keybinding-file'
import { WORKSPACE_GIT_IGNORE_COMMAND_SPECS } from './workspace-git-ignore'
import { WORKSPACE_GIT_GENERATION_COMMAND_SPECS } from './workspace-git-generation'
import type { CommandSpec } from '../args'
import { WORKSPACE_HOSTED_REVIEW_COMMAND_SPECS } from './workspace-hosted-review'
import { WORKSPACE_BITBUCKET_COMMAND_SPECS } from './workspace-bitbucket'
import { WORKSPACE_CATALOG_COMMAND_SPECS } from './workspace-catalog'
import { WORKSPACE_FILE_COMMAND_SPECS } from './workspace-file'
import { WORKSPACE_GIT_READ_COMMAND_SPECS } from './workspace-git-read'
import { WORKSPACE_GIT_WRITE_COMMAND_SPECS } from './workspace-git-write'
import { WORKSPACE_FOLDER_COMMAND_SPECS } from './workspace-folder'
import { WORKSPACE_PROJECT_GROUP_COMMAND_SPECS } from './workspace-project-group'
import { WORKSPACE_REPO_DATA_COMMAND_SPECS } from './workspace-repo-data'
import { WORKSPACE_PROJECT_DATA_COMMAND_SPECS } from './workspace-project-data'
import { WORKSPACE_PORTS_COMMAND_SPECS } from './workspace-ports'
import { WORKSPACE_GITHUB_ISSUE_COMMAND_SPECS } from './workspace-github-issue'
import { WORKSPACE_GITHUB_REVIEW_COMMAND_SPECS } from './workspace-github-review'
import { WORKSPACE_GITHUB_REVIEW_READ_COMMAND_SPECS } from './workspace-github-review-read'
import { WORKSPACE_GITHUB_WORK_ITEMS_COMMAND_SPECS_1 } from './workspace-github-work-items-1'
import { WORKSPACE_GITHUB_WORK_ITEMS_COMMAND_SPECS_2 } from './workspace-github-work-items-2'
import { WORKSPACE_GITHUB_PROJECT_COMMAND_SPECS_1 } from './workspace-github-project-1'
import { WORKSPACE_GITHUB_PROJECT_COMMAND_SPECS_2 } from './workspace-github-project-2'
import { WORKSPACE_GITLAB_COMMAND_SPECS_1 } from './workspace-gitlab-1'
import { WORKSPACE_GITLAB_COMMAND_SPECS_2 } from './workspace-gitlab-2'
import { WORKSPACE_GITLAB_COMMAND_SPECS_3 } from './workspace-gitlab-3'
import { WORKSPACE_JIRA_COMMAND_SPECS_1 } from './workspace-jira-1'
import { WORKSPACE_JIRA_COMMAND_SPECS_2 } from './workspace-jira-2'
import { WORKSPACE_LINEAR_DATA_COMMAND_SPECS } from './workspace-linear-data'
import { WORKSPACE_INTEGRATION_COMMAND_SPECS } from './workspace-integrations'

export const WORKSPACE_DATA_COMMAND_SPECS: CommandSpec[] = [
  ...WORKSPACE_GIT_STATUS_COMMAND_SPECS,
  ...WORKSPACE_LOG_TAIL_COMMAND_SPECS,
  ...WORKSPACE_NOTEBOOK_KERNEL_COMMAND_SPECS,
  ...WORKSPACE_LOCAL_CLONE_COMMAND_SPECS,
  ...WORKSPACE_REMOTE_CLONE_COMMAND_SPECS,
  ...WORKSPACE_FILE_SEARCH_COMMAND_SPECS,
  ...WORKSPACE_NESTED_SCAN_COMMAND_SPECS,
  ...WORKSPACE_FILE_LIST_COMMAND_SPECS,
  ...WORKSPACE_DESKTOP_ADOPT_COMMAND_SPECS,
  ...WORKSPACE_DESKTOP_REMOVE_COMMAND_SPECS,
  ...WORKSPACE_DESKTOP_CREATE_COMMAND_SPECS,
  ...WORKSPACE_LINEAGE_COMMAND_SPECS,
  ...WORKSPACE_SPACE_SCAN_COMMAND_SPECS,
  ...WORKSPACE_LOCALHOST_LABEL_COMMAND_SPECS,
  ...WORKSPACE_GITHUB_REFRESH_COMMAND_SPECS,
  ...WORKSPACE_REPO_CREATE_REMOTE_COMMAND_SPECS,
  ...WORKSPACE_REPO_ADD_COMMAND_SPECS,
  ...WORKSPACE_REPO_FOLDER_PICKER_COMMAND_SPECS,
  ...WORKSPACE_WORKTREE_FORGET_COMMAND_SPECS,
  ...WORKSPACE_CLEANUP_SCAN_COMMAND_SPECS,
  ...WORKSPACE_REPO_ICON_PICKER_COMMAND_SPECS,
  ...WORKSPACE_DIAGNOSTIC_PREVIEW_COMMAND_SPECS,
  ...WORKSPACE_NOTEBOOK_ENVIRONMENT_COMMAND_SPECS,
  ...WORKSPACE_SHELL_ACTION_COMMAND_SPECS,
  ...WORKSPACE_VISIBLE_WORKTREE_COMMAND_SPECS,
  ...WORKSPACE_DESKTOP_META_COMMAND_SPECS,
  ...WORKSPACE_REPO_USERNAME_COMMAND_SPECS,
  ...WORKSPACE_REPO_UPDATE_COMMAND_SPECS,
  ...WORKSPACE_IMPORT_PREVIEW_COMMAND_SPECS,
  ...WORKSPACE_HOST_PATH_COMMAND_SPECS,
  ...WORKSPACE_CRASH_REPORT_COMMAND_SPECS,
  ...WORKSPACE_GIT_STARTUP_COMMAND_SPECS,
  ...WORKSPACE_LINEAR_ISSUE_COMMAND_SPECS,
  ...WORKSPACE_CACHED_SCAN_COMMAND_SPECS,
  ...WORKSPACE_CLEANUP_DISMISSAL_COMMAND_SPECS,
  ...WORKSPACE_GITHUB_ACCOUNT_COMMAND_SPECS,
  ...WORKSPACE_GITLAB_INSPECTION_COMMAND_SPECS,
  ...WORKSPACE_KEYBINDING_FILE_COMMAND_SPECS,
  ...WORKSPACE_GIT_IGNORE_COMMAND_SPECS,
  ...WORKSPACE_GIT_GENERATION_COMMAND_SPECS,
  ...WORKSPACE_HOSTED_REVIEW_COMMAND_SPECS,
  ...WORKSPACE_BITBUCKET_COMMAND_SPECS,
  ...WORKSPACE_CATALOG_COMMAND_SPECS,
  ...WORKSPACE_FILE_COMMAND_SPECS,
  ...WORKSPACE_GIT_READ_COMMAND_SPECS,
  ...WORKSPACE_GIT_WRITE_COMMAND_SPECS,
  ...WORKSPACE_FOLDER_COMMAND_SPECS,
  ...WORKSPACE_PROJECT_GROUP_COMMAND_SPECS,
  ...WORKSPACE_REPO_DATA_COMMAND_SPECS,
  ...WORKSPACE_PROJECT_DATA_COMMAND_SPECS,
  ...WORKSPACE_PORTS_COMMAND_SPECS,
  ...WORKSPACE_GITHUB_ISSUE_COMMAND_SPECS,
  ...WORKSPACE_GITHUB_REVIEW_COMMAND_SPECS,
  ...WORKSPACE_GITHUB_REVIEW_READ_COMMAND_SPECS,
  ...WORKSPACE_GITHUB_WORK_ITEMS_COMMAND_SPECS_1,
  ...WORKSPACE_GITHUB_WORK_ITEMS_COMMAND_SPECS_2,
  ...WORKSPACE_GITHUB_PROJECT_COMMAND_SPECS_1,
  ...WORKSPACE_GITHUB_PROJECT_COMMAND_SPECS_2,
  ...WORKSPACE_GITLAB_COMMAND_SPECS_1,
  ...WORKSPACE_GITLAB_COMMAND_SPECS_2,
  ...WORKSPACE_GITLAB_COMMAND_SPECS_3,
  ...WORKSPACE_JIRA_COMMAND_SPECS_1,
  ...WORKSPACE_JIRA_COMMAND_SPECS_2,
  ...WORKSPACE_LINEAR_DATA_COMMAND_SPECS,
  ...WORKSPACE_INTEGRATION_COMMAND_SPECS
]
